- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: False
  
  tasks:
    - name: Set pagename variable
      set_fact:
        pagename: deadbears
    - name: Set suffix variable
      set_fact:
        suffix: de
    - name: Set dnsname variable
      set_fact:
        dnsname: deadbears.de
    - name: Set tCustomer variable
      set_fact:
        tCustomer: dead_and_bears
    - name: Set tName variable
      set_fact:
        tName: "{{ pagename }}-{{ lookup('env','CIRCLE_BRANCH') }}-{{ lookup('env','CIRCLE_BUILD_NUM') }}"
    - name: Set tVersion variable
      set_fact:
        tVersion: "{{ pagename }}-{{ lookup('env','CIRCLE_SHA1') }}"
    - name: Set tGit variable
      set_fact:
        tGit: "{{ lookup('env','CIRCLE_REPOSITORY_URL') }}"
        
    - name: Install AWSCLI
      pip: name=awscli state=present
    - name: Install boto
      pip: name=boto state=present
    - name: Install boto3
      pip: name=boto3 state=present
    - name: Install botocore
      pip: name=botocore state=present

    - name: obtain all facts for a single ACM certificate
      aws_acm_facts:
        domain_name: "{{ pagename }}.{{ suffix }}"
        region: us-east-1
      register: cert_details_0
    - name: Create acm cert request
      when: cert_details_0.certificates[0] is not defined
      shell: >
        aws acm request-certificate --domain-name {{ pagename }}.{{ suffix }}
        --validation-method DNS
        --subject-alternative-names www.{{ pagename }}.{{ suffix }}
        --idempotency-token {{ pagename }}
        --region us-east-1
      register: cert
    - name: Safe cert details (new cert)
      when: cert_details_0.certificates[0] is not defined
      set_fact:
        acm_item_cert_arn: "{{ (cert.stdout|from_json).CertificateArn }}"
    - name: Safe cert details (old cert)
      when: cert_details_0.certificates[0] is defined
      set_fact:
        acm_item_cert_arn: "{{ cert_details_0.certificates[0].certificate_arn }}"
    - name: Add tags acm cert request
      shell: >
        aws acm add-tags-to-certificate --certificate-arn {{ acm_item_cert_arn }}
        --tags Key=Customer,Value={{ tCustomer }} Key=Name,Value={{ tName }} Key=Version,Value={{ tVersion }} Key=Git,Value={{ tGit }}
        --region us-east-1
    - name: Create an Bucket
      s3_bucket:
        name: "{{ pagename }}"
        region: eu-central-1
        tags:
          Customer: "{{ tCustomer }}"
          Name: "{{ tName }}"
          Version: "{{ tVersion }}"
          Git: "{{ tGit }}"
      register: bucket_details
    - name: Configure bucket as website
      s3_website :
        name: "{{ pagename }}"
        region: eu-central-1
        error_key: 404.html
        state: present
    - name: Configure CORS on the bucket
      aws_s3_cors:
        name: "{{ pagename }}"
        state: present
        region: eu-central-1
        rules:
          - allowed_origins:
              - "*"
            allowed_methods:
              - GET
            allowed_headers:
              - "*"
    - name: Upload files
      s3_sync:
        bucket: "{{ pagename }}"
        region: eu-central-1
        file_root: ../target/
        permission: public-read
        cache_control: "public, max-age=31536000, immutable"
        file_change_strategy: checksum
        mode: push
        include: "*"
        exclude: ".*,*.html,icon-*.png,idb-keyval-iife.min.js,sw.js,chunk-map.json,manifest.webmanifest,robots.txt,sitemap.xml,webpack.stats.json"
    - name: Upload files
      s3_sync:
        bucket: "{{ pagename }}"
        region: eu-central-1
        file_root: ../target/
        permission: public-read
        cache_control: "public, max-age=0, s-maxage=31536000, must-revalidate, stale-while-revalidate=2628000, stale-if-error=604800"
        file_change_strategy: checksum
        mode: push
        include: "*.html,icon-*.png,idb-keyval-iife.min.js,sw.js,SHAs.json,chunk-map.json,manifest.webmanifest,robots.txt,sitemap.xml,webpack.stats.json"
        exclude: ".*"
    - name: PUT sw.js with different meta data
      aws_s3:
        bucket: "{{ pagename }}"
        object: /sw.js
        src: ../target/sw.js
        permission: public-read
        mode: put
        region: eu-central-1
        encrypt: no
        metadata: 'Cache-Control="public, max-age=0, s-maxage=31536000, must-revalidate, stale-if-error=604800"'
    - name: obtain all facts for a single ACM certificate
      aws_acm_facts:
        domain_name: "{{ pagename }}.{{ suffix }}"
        region: us-east-1
      register: cert_details
    - name: Creat DNS entry 1
      uri:
        url: "https://dns.api.gandi.net/api/v5/domains/{{ dnsname }}/records"
        method: POST
        body: "{
             \"rrset_name\": \"{{ cert_details.certificates[0].domain_validation_options[0].resource_record.name }}\",
             \"rrset_type\": \"{{ cert_details.certificates[0].domain_validation_options[0].resource_record.type }}\",
             \"rrset_values\": [\"{{ cert_details.certificates[0].domain_validation_options[0].resource_record.value }}\"],
             \"rrset_ttl\": 3600
             }"
        status_code: 201, 200
        body_format: json
        headers:
          Content-Type: "application/json"
          X-Api-Key: "{{ lookup('env','GANDI') }}"
    - name: Creat DNS entry 2
      uri:
        url: "https://dns.api.gandi.net/api/v5/domains/{{ dnsname }}/records"
        method: POST
        body: "{
             \"rrset_name\": \"{{ cert_details.certificates[0].domain_validation_options[1].resource_record.name }}\",
             \"rrset_type\": \"{{ cert_details.certificates[0].domain_validation_options[1].resource_record.type }}\",
             \"rrset_values\": [\"{{ cert_details.certificates[0].domain_validation_options[1].resource_record.value }}\"],
             \"rrset_ttl\": 3600
             }"
        status_code: 201, 200
        body_format: json
        headers:
          Content-Type: "application/json"
          X-Api-Key: "{{ lookup('env','GANDI') }}"
    - name: Wait some second for dns to propagate
      wait_for: timeout=10
      delegate_to: localhost
    - name: Wait for cert grant
      shell: >
        aws acm wait certificate-validated --certificate-arn {{ acm_item_cert_arn }} --region us-east-1
    - name: Wait some second until certificate grant has propagated
      wait_for: timeout=10
      delegate_to: localhost
    - name: Setup cloudfront
      register: cloudfrontdistribution
      cloudfront_distribution:
        state: present
        enabled: yes
        origins: 
          - domain_name: "{{ pagename }}.s3-website.eu-central-1.amazonaws.com"
            id: "{{ pagename }}"
            custom_origin_config:
              origin_protocol_policy: http-only
        aliases: [ '{{ pagename }}.{{ suffix }}', 'www.{{ pagename }}.{{ suffix }}' ]
        viewer_certificate:
          acm_certificate_arn: "{{ acm_item_cert_arn }}"
          certificate : "{{ acm_item_cert_arn }}"
          certificate_source: acm
          ssl_support_method: sni-only
          minimum_protocol_version: "TLSv1.2_2018"
        default_root_object: index.html
        ipv6_enabled: yes
        custom_error_responses:
          - response_code: 404
            error_caching_min_ttl: 3600
            response_page_path: '/404.html'
            error_code: 403
          - response_code: 404
            error_caching_min_ttl: 3600
            response_page_path: '/404.html'
            error_code: 404
        tags:
          Name: "{{ tName }}"
          Version: "{{ tVersion }}"
          Git: "{{ tGit }}"
          Customer: "{{ tCustomer }}"
        default_cache_behavior:
          target_origin_id: "{{ pagename }}"
          compress: true
          viewer_protocol_policy: redirect-to-https
          lambda_function_associations:
            - lambda_function_arn: arn:aws:lambda:us-east-1:157114673671:function:addSecurityHeaders:17
              event_type: origin-response
          forwarded_values:
            query_string: false
            cookies:
              forward: none
            headers:
             - 'Origin'
             - 'Access-Control-Request-Headers'
             - 'Access-Control-Request-Method'
          allowed_methods:
            items:
              - GET
              - HEAD
              - OPTIONS
            cached_methods:
              - GET
              - HEAD
              - OPTIONS
    - name: create a batch of invalidations using a distribution_id for a reference
      when: "'diff' in cloudfrontdistribution"
      cloudfront_invalidation:
        alias: 'www.{{ pagename }}.{{ suffix }}'
        target_paths:
          - /*
    - name: Obtain cloudfront url for cname
      register: cloudfront_details
      cloudfront_facts:
        distribution: true
        domain_name_alias: www.{{ pagename }}.{{ suffix }}
    - name: Switch dns entry over (www)
      uri:
        url: "https://dns.api.gandi.net/api/v5/domains/{{ dnsname }}/records/www.{{ pagename }}.{{ suffix }}./CNAME"
        method: PUT
        body: "{
             \"rrset_values\": [\"{{ ansible_facts['cloudfront'][pagename + '.' + suffix].Distribution.DomainName }}.\"],
             \"rrset_ttl\": 86400
             }"
        status_code: 201, 200
        body_format: json
        headers:
          Content-Type: "application/json"
          X-Api-Key: "{{ lookup('env','GANDI') }}"
    - name: Wait some second for dns to propagate
      wait_for: timeout=10
      delegate_to: localhost
    - name: Switch dns entry over (no www)
      uri:
        url: https://dns.api.gandi.net/api/v5/domains/{{ dnsname }}/records/{{ pagename }}.{{ suffix }}./CNAME
        method: PUT
        body: "{
             \"rrset_values\": [\"{{ ansible_facts['cloudfront'][pagename + '.' + suffix].Distribution.DomainName }}.\"],
             \"rrset_ttl\": 86400
             }"
        status_code: 201, 200
        body_format: json
        headers:
          Content-Type: "application/json"
          X-Api-Key: "{{ lookup('env','GANDI') }}"     
        
